### ISSUE TITLE
Autoencoder vs VAE [question]

### ISSUE THREAD

**Issue by el-cangrejo** [araffin/srl-zoo#24]
Hello, I trained two state representation models, one with the **vae** loss and one with the **autoencoder** loss, both on the KukaRandButtonGymEnv-v0 and for the same number of epochs (5) and state dims (5). The vae model reconstructs very poorly the input image compared to the autoencoder:

vae:
![selection_001](https://user-images.githubusercontent.com/6048578/47934628-af925700-decf-11e8-8285-2e78e76fe5d5.png)

autoencoder:
![selection_002](https://user-images.githubusercontent.com/6048578/47934645-bb7e1900-decf-11e8-8f5f-40130147b2dc.png)

It seems like it's producing an average over the dataset. Does it sample from the data likelihood distribution or does it calculate the mean value of p(x|z)?

Also when visualizing the learned space with the enjoy_latent module I noticed that the states of the autoencoder have a wide range (for example [-20, 20]) and the produced visualizations are quite different. On the other hand the states for the vae  have a very narrow range (for example [-0.04, 0.04]) and the produced visualizations are almost identical.  Is this an expected behavior?

Autoencoder (min, max):
![selection_005](https://user-images.githubusercontent.com/6048578/47935178-71963280-ded1-11e8-84db-1372bce224c1.png)

![selection_006](https://user-images.githubusercontent.com/6048578/47935184-75c25000-ded1-11e8-9942-24c9ec91ddbf.png)

VAE (min, max):
![selection_007](https://user-images.githubusercontent.com/6048578/47935194-7d81f480-ded1-11e8-8828-16103e33b6e9.png)

![selection_008](https://user-images.githubusercontent.com/6048578/47935197-81157b80-ded1-11e8-8d24-40f18b8c8f95.png)

**Comment by araffin** [comment]
Hello,

>The vae model reconstructs very poorly the input image compared to the autoencoder:
>Also when visualizing the learned space with the enjoy_latent module I noticed that the states of the autoencoder have a wide range

I would say those two behaviors are expected. The VAE has an additional KL loss, so its latent space distribution approximates a multi-dimensional gaussian with a unit standard deviation. This loss is combined with the reconstruction loss, so they may interfere: as it adds a new constrain, it is harder for the VAE to reconstruct the image. The KL loss also explains the bounds of the VAE latent space: the AE is not penalized when its latent space has a wide range, but this is true for the VAE.

In your case, I would try to add more dimensions (so it is easier for the VAE to reconstruct the image), more epochs, and maybe play with the \beta coefficient (which weights the importance of the KL loss and reconstruction loss). Btw, how many samples are you using for training?

>Does it sample from the data likelihood distribution or does it calculate the mean value of p(x|z)?

It samples, the corresponding line: https://github.com/araffin/srl-zoo/blob/master/evaluation/enjoy_latent.py#L35

**Comment by el-cangrejo** [comment]
Hi, thanks for the quick response. I'm using 1568 samples. I'll try with more dimensions, samples and epochs and see how it goes. Do you provide any way to visualize a "combined" model? I'm trying to implement something like the _World Models_ model so I trained a model with the forward and autoencoder loss and I would like the the forward model to predict the next state given the current and an action and the autoencoder to reconstruct the observation from the state.

**Comment by araffin** [comment]
>Do you provide any way to visualize a "combined" model? 

We provide way to visualize combined models when combined means combining a method with a decoder (=auto-encoder) with another loss (ex: inverse dynamics, where we use knn on the dataset).
However, we don't provide visualization for future observation, but it should not be too hard to integrate.

Feel free to submit a PR if you integrate it ;)

**Comment by el-cangrejo** [comment]
Okay thanks!

**Comment by ncble** [comment]
Actually, about the VAE and autoencoder, I have recently discovered a bug (see the issue [#53](https://github.com/araffin/robotics-rl-srl/issues/53)). By  fixing this bug, I have successfully reconstructed image with VAE:

![recons_30](https://user-images.githubusercontent.com/28021952/60514445-c9dc3900-9cd9-11e9-9ffc-277edf753184.png)

The left two images are original images, and the right two are reconstructed. Without my fix as described in [#53](https://github.com/araffin/robotics-rl-srl/issues/53), I got similar result to your images. So it's definitely the source of your problem.
